### ISSUE TITLE
Use HTTP requests from a django-security library if available

### ISSUE THREAD

**Issue by asgeirrr** [matllubos/django-ats-sms-operator#2]
See https://bitbucket.org/usertech/kup-najisto/pull-requests/1411/knj-1780-new-version-of-django-reversion/diff

**Comment by matllubos** [comment]
what?

**Comment by asgeirrr** [comment]
Requests should be logged, therefore we ought to use put, post, etc. methods from django-security if that library is available. It was your suggestion in the aforementioned PR.

**Comment by asgeirrr** [comment]
Already solved.
